version: '3'

services:
  admin:
    build:
      dockerfile: Dockerfile.dev
    environment:
      APP_ENV: development
    volumes:
      - ../project/admin:/usr/src/app
      - /usr/src/admin/node_modules
      - /usr/src/admin/.next