version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile.dev
    environment:
      APP_ENV: development
    volumes:
      - ../project/api:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next